server:
  port: 8088
spring:
  application:
    name: config-demo
alibaba:
  acm:
    group: DEFAULT_GROUP
    endpoint: acm.aliyun.com
    namespace: namespace
    access-key: access-key
    secret-key: secret-key
    application-data-id: top.vchar.demo:config-demo.yml
    data-id-list: demo.yml,dev.properties
